services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    extra_hosts:
      # Supaya container bisa akses host machine (Redis & PostgreSQL yang sudah running)
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    ports:
      - "8001:8001" # FastAPI health + metrics
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  metrics:
    build:
      context: ./metrics
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
